name: Azure Terraform Export

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read

jobs:
  terraform-export:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install aztfexport
        run: |
          curl -L https://github.com/Azure/aztfexport/releases/latest/download/aztfexport-linux-amd64.tar.gz -o aztfexport.tar.gz
          tar -xzf aztfexport.tar.gz
          chmod +x aztfexport
          sudo mv aztfexport /usr/local/bin/
          aztfexport --version


      - name: Azure Login
        run: |
          az login --service-principal --username 301cb20d-21f4-4cbc-ad84-dcddb6852f1c --password 87b8Q~LfR1QUpJdbzJx_u3tRhQ3JN7Wm5IzJHcow --tenant c18f87b5-3033-4e25-aa12-5641175188ba
          az extension add --name resource-graph
          az extension add --name terraform

      - name: Run Terraform Export
        run: |
          bash scripts/export-terraform.sh

      - name: Upload Terraform Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: terraform-export
          path: terraform-export
